[package]
name = "timezone_db"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = "1.0"
serde_urlencoded = "0.7"
urlencoding = "2.1"
lazy_static = "1.4"
thiserror = "1.0"
jwt = "0.16"
hmac = "0.12"
sha2 = "0.10"

